### PR TITLE
chore: Clarify comment in exercises/test1.rs

### LINKED ISSUE #194: exercises/test1.rs has tests reversed
As given, the correct answer fails. The assertions should be reversed:

```rust
fn verify_test() {
    let price1 = calculate_price(55);
    let price2 = calculate_price(40);

    assert_eq!(price1, 110);
    assert_eq!(price2, 40);
}
```

### PR DESCRIPTION
**Pull request by ssweeny**
closes #194

The author of issue #194 suggests that the wording of the comment is at
least ambiguous about the desired results. I believe this change more
clearly describes the expectation of the exercise.

### CODE REVIEW

**Comment by fmoko** [comment]
fixed in https://github.com/rust-lang/rustlings/commit/79a569422c8309cfc9e4aed25bf4ab3b3859996b, sorry about that!

**Comment by ssweeny** [comment]
I must have been tired when I read the issue and thought I could post a quick fix. Sorry for the churn!

**Comment by fmoko** [comment]
@ssweeny no big deal!

**Pull request merged**
