### PR TITLE
Fix quiz1 description

### PR DESCRIPTION
**Pull request by ceth-x86**
Description:

> but if you buy 40 or more at once, each apple only costs 1

Code:

```rs
let price2 = calculate_price_of_apples(40);
assert_eq!(80, price2);
```

I get 40 apples. It equals to 40 ("40 or more at once" -> true). So each apple cost 1 bucks and the answer must be 40 for current condition.

### CODE REVIEW

**Comment by Evgeny-SPB** [comment]
This pull request is a duplicate of https://github.com/rust-lang/rustlings/pull/1170

**Comment by robinvandernoord** [comment]
Agreed, I was confused my test was failing as well. Either the test or the description should be updated

**Comment by satyambnsal** [comment]
> Description:
> 
> > but if you buy 40 or more at once, each apple only costs 1
> 
> Code:
> 
> ```rust
> let price2 = calculate_price_of_apples(40);
> assert_eq!(80, price2);
> ```
> 
> I get 40 apples. It equals to 40 ("40 or more at once" -> true). So each apple cost 1 bucks and the answer must be 40 for current condition.

lol was about to raise PR for the same 😂

**Comment by diannasoreil** [comment]
Fixed on main

**Pull request closed without merging**
