### PR TITLE
Add CodeCrafters

### PR DESCRIPTION
**Pull request by sarupbanskota**
Jon Gjengset recently made a [video](https://www.youtube.com/watch?v=jf_ddGnum_4&t=232s&ab_channel=JonGjengset) streaming the Build your own BitTorrent challenge in Rust.

### CODE REVIEW

**Comment by shadows-withal** [comment]
I'm hesitant about adding non-"officially endorsed" resources here - the intent is for this section to be in sync with what the official learning page (https://rust-lang.org/learn) says.

**Comment by shadows-withal** [comment]
I wouldn't be opposed to putting it in the "Continuing on" section, assuming CodeCrafters has sufficiently advanced materials for people who have finished Rustlings?

**Comment by sarupbanskota** [comment]
Good idea! CodeCrafters is almost the perfect resource for the Continuing On section. Many people actually do it after they do Rustlings. [Just made a PR](https://github.com/rust-lang/rustlings/pull/1760), please feel free to merge it or suggest any formatting revisions.

**Comment by Adesoji1** [comment]
beatiful

**Pull request closed without merging**
