### PR TITLE
Add two trait-related exercises

### PR DESCRIPTION
**Pull request by s-marios**
Currently rustlings is lacking any exercises dealing with traits. To address this, I'm submitting two exercises related to implementing a simple trait.

### CODE REVIEW

**Comment by s-marios** [comment]
Any interest in this?

**Comment by fmoko** [comment]
Hi @s-marios! Sorry for the delay, I unfortunately can't dedicate as much time as I'd want towards maintaining this project. That being said, I'd love to have your exercises in Rustlings. Judging by the merge conflict we have for this pull request, we've since changed the way hints are handled (they are now sourced from `info.toml` instead of the file itself). If you update the exercises to match this, I'd be happy to merge it. More info for this can be found in our [contributing document](https://github.com/rust-lang/rustlings/blob/master/CONTRIBUTING.md#adding-an-exercise). Thanks!

**Comment by sjmann** [comment]
@fmoko @s-marios can I pick this up and try to resolve the conflicts for you? I would like to do the traits exercises so I will do it locally anyway

**Comment by fmoko** [comment]
Closed by #274!

**Comment by s-marios** [comment]
> @fmoko @s-marios can I pick this up and try to resolve the conflicts for you? I would like to do the traits exercises so I will do it locally anyway

Thanks for going through the trouble! Cheers!

**Pull request closed without merging**
