### PR TITLE
Convert exercises with assertions to tests

### PR DESCRIPTION
**Pull request by mo8it**
Converted all exercises having assertions to test mode.

I am not really sure about all implications of this conversion. Please review it first. You might think that some of them should have both a main function and a test.

Should the function names be changed? `main` is not a good test function name. I can use other names if you want.

### CODE REVIEW

**Review by shadows-withal — APPROVED** [review]
yep, I agree with this rationale

**Comment by shadows-withal** [comment]
that being said, I think it's fine to keep `main` as a test name

**Comment by mo8it** [comment]
Alright, the PR would be ready for merging then after your review, right? :D

**Comment by shadows-withal** [comment]
Oh yeah sure! Let me do that.

**Pull request merged**
