### PR TITLE
Update iterator solution in quiz2.rs

### PR DESCRIPTION
**Pull request by NewtonChutney**
The iterator solution uses a for loop in its body, to the dismay of functional programmers.. 🫠
We could use the repeat method in this situation!

### CODE REVIEW

**Comment by mo8it** [comment]
I was against `str::repeat` because it allocates a `String` first.

But I just benchmarked both methods and `repeat` seems to be more efficient. The checks while appending a `&str` in the loop seem to cost more than the temporary allocation.

**Comment by mo8it** [comment]
Complete with https://github.com/rust-lang/rustlings/commit/0f4cb94cfe31745e8fee9efc7dc1d287e65e16cb

**Comment by NewtonChutney** [comment]
> I was against `str::repeat` because it allocates a `String` first.
> 
> But I just benchmarked both methods and `repeat` seems to be more efficient. The checks while appending a `&str` in the loop seem to cost more than the temporary allocation.

Isn't this the case generally? I remember reading about this somewhere.. 🤔
That functional style programming in Rust at least as efficient as the elaborated for loop..

**Comment by mo8it** [comment]
This is at least the case with iterators over loops.
But `str::repeat` has nothing to do with iterators. In fact, `str::repeat` is implemented over `slice::repeat` which itself is [implemented using a loop](https://github.com/rust-lang/rust/blob/7fdefb804ec300fb605039522a7c0dfc9e7dc366/library/alloc/src/slice.rs#L510-L566) in the standard library. This case is not about functional vs imperative.

**Comment by NewtonChutney** [comment]
> This is at least the case with iterators over loops. But `str::repeat` has nothing to do with iterators. In fact, `str::repeat` is implemented over `slice::repeat` which itself is [implemented using a loop](https://github.com/rust-lang/rust/blob/7fdefb804ec300fb605039522a7c0dfc9e7dc366/library/alloc/src/slice.rs#L510-L566) in the standard library. This case is not about functional vs imperative.

Ahh.. thanks for pointing it out. TIL

I need to look into the standard library's implementations more.. 😅

**Pull request merged**
