### PR TITLE
fix(cli): Move long text strings into constants.

### PR DESCRIPTION
**Pull request by apogeeoak**
Moved `DEFAULT_OUT` text from a separate file into a constant. Moved `FENISH_LINE` and `WELCOME` text from `println!` statements into constants.

The constants are defined at the end of the file because they are so long.

### CODE REVIEW

**Comment by diannasoreil** [comment]
@apogeeoak Any interest in fixing the merge conflict so I can merge this? Otherwise I'll do it myself :)

**Comment by apogeeoak** [comment]
I can fix the conflicts this weekend.

**Comment by apogeeoak** [comment]
@diannasoreil All merge conflicts are fixed. This is ready for review again.

**Review by diannasoreil — APPROVED** [review]
Thanks!

**Pull request merged**
