### PR TITLE
feature: added exercise to "traits" chapter

### PR DESCRIPTION
**Pull request by abhi3700**
This is an attempt to add 1 exercise in "traits" chapter.

The objective is to let the developer learn these:
- "How to implement at function that can return incompatible types?"
- "How to make the same function printable on console?"

Looking forward to getting feedback on this.

### CODE REVIEW

**Comment by poneciak57** [comment]
Exercise `traits6` is unnecessarily large, tests seems redundant here.

**Comment by abhi3700** [comment]
> Exercise `traits6` is unnecessarily large, tests seems redundant here.

I can add ?? in tests.

Or I just have only ‘traits7.rs’

**Comment by poneciak57** [comment]
I think u can just delete tests and add main function with simple showcase.

**Comment by abhi3700** [comment]
> I think u can just delete tests and add main function with simple showcase.

ok followed

**Pull request closed without merging**
