### PR TITLE
Introduce a Pointers section

### PR DESCRIPTION
**Pull request by TheLe0**
This is a very important topic to have, because great programmers need to understand pointers, because they help a lot
to understand how low level code works.

### CODE REVIEW

**Comment by fmoko** [comment]
Thanks for your pull request! Unfortunately, I have to say I'm opposed to the inclusion of pointers in Rustlings, as it's not a very common use case to directly interface with them, and you can accomplish 99% of all things in Rust without ever touching raw pointers (in fact, this is one of the strong suits of Rust's memory management model - being able to have granular memory management without having to use pointers directly). The only thing that might be useful to know in relation to pointers is dereferencing, but I don't see it worth adding that in scope of this PR.

**Comment by fmoko** [comment]
(Also, I wouldn't agree that "great programmers need to know how pointers work", you don't need to know all low level concepts to be a great programmer. If you're into low level systems programming, sure, it's important to know how pointers work, but I still believe that many people would find this topic's inclusion into Rustlings more confusing than helpful)

**Comment by jrvidal** [comment]
(Side note: "pointer" in Rust usually refers to "raw pointer", while this exercise is about references. Though their semantics are quite similar, the current terminology is potentially confusing).

**Comment by TheLe0** [comment]
I presume this was a rejection, so i'm going to close this.
Thanks for your time!
cheers!

**Pull request closed without merging**
