### PR TITLE
feat(cli): Added 'cls' command to 'watch' mode

### PR DESCRIPTION
**Pull request by DeepSpace2**
feat(cli): Added 'cls' command to 'watch' mode

### CODE REVIEW

**Comment by fmoko** [comment]
Personally, I'd prefer `clear` instead of `cls`. Any reason why you've called it that?

**Comment by DeepSpace2** [comment]
@fmoko Not really, we can change it to what the consensus will be. May be even both :)

**Comment by fmoko** [comment]
@DeepSpace2 I think just 'clear' would be fine :) Thanks!

**Comment by DeepSpace2** [comment]
@fmoko fixed, changed to 'clear' :)

**Pull request merged**
