### PR TITLE
Add rust-analyzer.toml file

### LINKED ISSUE #2104: #[warn(dead_code)] showing unnecessary x is never used warnings
Since testing in some exercises is done using tests modules, annoying `function 'x' is never used warning` shows while and after solving the exercise...
image

Which could sometimes be annoying or even come before/hide more relevant code lints related to the main exercise issue:

Before: 
before
After: 
after

A simple way to make it look cleaner is by adding `#![allow(dead_code)]` to all files which have `mod tests {`

```rust
| #![allow(dead_code)]

  fn fill_vec(vec: Vec<i32>) -> Vec<i32> {
      let mut vec = vec;

      vec.push(88);

      vec
  }
  ...
```

Or in a more generic/centralized way in `Cargo.toml`

```toml
[lints.rust]
usued = "allow"
```
```[tasklist]
### Solutions
- [ ] https://github.com/rust-lang/rustlings/pull/2105
- [ ] https://github.com/rust-lang/rustlings/pull/2106
```

### PR DESCRIPTION
**Pull request by alibektas**
Fixes #2104.

### CODE REVIEW

**Comment by alibektas** [comment]
Just my amateur solution to this problem. Let me know if you have any stylistic changes you want me to make :wave:

**Comment by mo8it** [comment]
Thanks!

We need the small file in the repo. We can define the content in a `&[u8]` constant and use it like `GITIGNORE`: https://github.com/rust-lang/rustlings/blob/1f624d4c2a4ee0441ffce842591a8e37e329d309/src/init.rs#L176

I wonder if `extraArgs` will stay as is or get renamed to `extra_args` since camel case is common in TOML files.

**Comment by alibektas** [comment]
> Thanks!
> 
> We don't need the small file in the repo. We can define the content in a `&[u8]` constant and use it like `GITIGNORE`:
> 
> https://github.com/rust-lang/rustlings/blob/1f624d4c2a4ee0441ffce842591a8e37e329d309/src/init.rs#L176
> 
> I wonder if `extraArgs` will stay as is or get renamed to `extra_args` since camel case is common in TOML files.

I don't think a renaming is among our plans. In either case we never remove old config names and check for them [too](https://github.com/rust-lang/rust-analyzer/blob/fd243cd0fbad8297e7a3c86f18aa5f0a110bb85f/crates/rust-analyzer/src/config.rs#L484).

**Comment by mo8it** [comment]
Tested the config in a `rust-analyzer.toml` file with the Rust-Analyzer extention in VS-Code (pre-release). It doesn't seem to work (yet?). See the screenshot where the function `bigger` is underlined. The warning is that this function isn't used. I restarted Rust-Analyzer after creating the config file and even restarted the whole editor. It doesn't seems to use that config.

Screenshot from 2024-09-13 13-48-54

**Comment by alibektas** [comment]
That's odd. I made the warning go away when I tried it in my local. I will have another look at it in a few hours.

**Comment by mo8it** [comment]
@alibektas Is `.rust-analyzer.toml` (with dot) also supported? It would be nice to be able to hide it from beginners.

**Comment by alibektas** [comment]
not yet and we didn't really plan such thing but I can see people asking for it so I will implement it in a few days. I am making an issue of it an pinging you.

**Pull request merged**
