### PR TITLE
fix: Include exercises folder in the project structure behind a feature

### LINKED ISSUE #859: error: “file not included in module tree”
When I open an exercise with Neovim(+Rust-analyzer) I get the (only) error “file not included in module tree” in the first line of the source file.

### LINKED ISSUE #913: Documentation doesn't show in VS code on hover
Difficult to do an excersize like this without any documentation. Should make rustlings compatible with extensions like rust-analyzer or Rust. 

image

### LINKED ISSUE #942: VSCode rust analyzer can not hint code under exercise folder

### PR DESCRIPTION
**Pull request by x-hgg-x**
closes #859
closes #913
closes #942

Related to #443 and #289.

This allows rust-analyzer to work normally after adding the setting `"rust-analyzer.cargo.features": ["exercises"]`.

### CODE REVIEW

**Comment by diannasoreil** [comment]
Does this require an adjustment on the user's side (just to make sure I'm understanding this correctly)? If so, can this specific configuration change for rust-analyzer be done per-project? I'm not too familiar with its configuration.

**Comment by x-hgg-x** [comment]
Yes you can set this setting per-project.
For Visual Studio Code you create the file `.vscode/settings.json` with the content:

```json
{
    "rust-analyzer.cargo.features": ["exercises"],
}
```

**Comment by x-hgg-x** [comment]
It also works in IntelliJ Rust without any settings since the plugin seems to run `cargo` with the ` --all-features` parameter by default.

**Comment by flaiker** [comment]
Found this PR after having no analysis in CLion and applying the patch seems to have fixed it perfectly without any additional configuration.

**Comment by diannasoreil** [comment]
Okay, so as long as you enable running either with all features or specifically that feature it works... I think that's a good enough compromise for us, given that we don't use the standard Rust directory layout in the first place. I'll merge this and document it in the README file.

**Comment by diannasoreil** [comment]
@all-contributors please add @x-hgg-x for code

**Comment by alexrecuenco** [comment]
It seems that this fix was later removed in ed0f278 for 5.x (https://github.com/rust-lang/rustlings/commit/ed0f278a8f116a1f69f20bba15485f019bfe2142)

Any reason why? 

Any documentation in what rustlings expect us to do with intellisense on the 5.x versions?

**Comment by shadows-withal** [comment]
@alexrecuenco This was our first implementation of LSP functionality, which we ended up removing in favor of https://github.com/rust-lang/rustlings#enabling-rust-analyzer.

**Pull request merged**
