### PR TITLE
feat: add lib

### PR DESCRIPTION
**Pull request by honeywest**

### CODE REVIEW

**Comment by mo8it** [comment]
May I ask why? 😅
I might be missing some advantage here.

**Comment by honeywest** [comment]
Code is easier to read and understand

**Comment by honeywest** [comment]
Code is easier to read and understand.
This structure is better, and the purpose here is to teach people how to learn rust

**Comment by mo8it** [comment]
I will leave the decision to @shadows-withal

**Comment by shadows-withal** [comment]
I think for people wanting to work on Rustlings itself, learning about the lib/main split is more confusing than convenient, and we derive no significant benefit from this (e.g. Rustlings is pretty much never going to be a "library"), so I'm gonna close this.

**Pull request closed without merging**
