### PR TITLE
feat: Add type conversion and parsing exercises

### PR DESCRIPTION
**Pull request by AbdouSeck**
This pull request adds exercises for converting values into specific types. The exercises uses string to struct type conversions, but most of the traits in the exercises can handle more than just string parsing and conversions.

The following traits are covered:
1. `From` and `Into`
2. `TryFrom` and `TryInto`
3. `AsRef`
4. `FromStr`

The `as` operator is also covered.

### CODE REVIEW

**Comment by fmoko** [comment]
Thanks!

@bors: r+

**Comment by fmoko** [comment]
@AbdouSeck Looks like you're missing the "I AM NOT DONE" comment in your exercises!

**Comment by AbdouSeck** [comment]
@fmoko I just added the lines to the exercise files. Please let me know if anything else looks amiss.

Thanks,

Abdou

**Pull request merged**
