### PR TITLE
fixed creating non pdb temps

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
On rust nightly on windows 10 x64 i see rustling produced files like `temp_7120` with no `*.pdb` which were not ignored                                                                                                                                                                                                                             

```


    Directory: D:\src\learning-rust\rustlings


Mode                 LastWriteTime         Length Name                                                                                                                                                                                                                                     
----                 -------------         ------ ----                                                                                                                                                                                                                                     
d-----        10/11/2020   9:33 AM                .ionide                                                                                                                                                                                                                                  
d-----        10/18/2020  10:09 AM                exercises                                                                                                                                                                                                                                
d-----         9/26/2020  10:05 AM                src                                                                                                                                                                                                                                      
d-----          9/7/2020   5:18 PM                target                                                                                                                                                                                                                                   
d-----         9/26/2020  10:05 AM                tests                                                                                                                                                                                                                                    
-a----         9/26/2020  10:05 AM          15859 .all-contributorsrc                                                                                                                                                                                                                      
-a----          9/7/2020   5:06 PM             88 .clog.toml                                                                                                                                                                                                                               
-a----          9/7/2020   5:06 PM            102 .editorconfig                                                                                                                                                                                                                            
-a----        10/18/2020  10:18 AM            117 .gitignore                                                                                                                                                                                                                               
-a----         9/26/2020  10:05 AM            175 .gitpod.yml                                                                                                                                                                                                                              
-a----         9/26/2020  10:05 AM            104 .replit                                                                                                                                                                                                                                  
-a----          9/7/2020   5:06 PM            147 buildkite.yml                                                                                                                                                                                                                            
-a----         9/26/2020  10:05 AM          42395 Cargo.lock                                                                                                                                                                                                                               
-a----         9/26/2020  10:05 AM            460 Cargo.toml                                                                                                                                                                                                                               
-a----         9/26/2020  10:05 AM          18704 CHANGELOG.md                                                                                                                                                                                                                             
-a----          9/7/2020   5:06 PM           4145 CONTRIBUTING.md                                                                                                                                                                                                                          
-a----          9/7/2020   5:06 PM            691 default_out.txt                                                                                                                                                                                                                          
-a----         9/26/2020  10:05 AM          29313 info.toml                                                                                                                                                                                                                                
-a----         9/26/2020  10:05 AM           3022 install.ps1                                                                                                                                                                                                                              
-a----         9/26/2020  10:05 AM           3787 install.sh                                                                                                                                                                                                                               
-a----          9/7/2020   5:06 PM           1095 LICENSE                                                                                                                                                                                                                                  
-a----         9/26/2020  10:05 AM          25200 README.md                                                                                                                                                                                                                                
-a----        10/18/2020  10:18 AM              0 temp_.txt                                                                                                                                                                                                                                
-a----        10/17/2020   8:02 PM         180736 temp_10284                                                                                                                                                                                                                               
-a----        10/17/2020   8:02 PM        2355200 temp_10284.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   4:23 PM        2355200 temp_12252.pdb                                                                                                                                                                                                                           
-a----        10/14/2020   9:24 PM        2297856 temp_13620.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   9:56 PM        2355200 temp_13884.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   2:19 PM        2355200 temp_15200.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   8:01 PM        1093632 temp_15460.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   7:52 PM        1093632 temp_1572.pdb                                                                                                                                                                                                                            
-a----          9/9/2020   6:12 PM        1069056 temp_16216.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   9:11 PM        2297856 temp_16972.pdb                                                                                                                                                                                                                           
-a----        10/14/2020   5:20 PM        2297856 temp_17128.pdb                                                                                                                                                                                                                           
-a----        10/14/2020   5:20 PM        2297856 temp_17368.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   8:13 PM        2355200 temp_17572.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   8:25 PM        1118208 temp_17632.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   8:18 PM         180736 temp_1772                                                                                                                                                                                                                                
-a----        10/17/2020   8:18 PM        2355200 temp_1772.pdb                                                                                                                                                                                                                            
-a----        10/17/2020   8:25 PM        1118208 temp_18348.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   8:27 PM        1118208 temp_18528.pdb                                                                                                                                                                                                                           
-a----        10/17/2020  11:26 AM        2355200 temp_22368.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   8:18 PM         180736 temp_22660                                                                                                                                                                                                                               
-a----        10/17/2020   8:18 PM        1110016 temp_22660.pdb                                                                                                                                                                                                                           
-a----        10/17/2020  11:28 AM        2355200 temp_23140.pdb                                                                                                                                                                                                                           
-a----        10/14/2020   5:18 PM        2297856 temp_23272.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   8:26 PM        1118208 temp_23540.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   8:11 PM         180736 temp_23808                                                                                                                                                                                                                               
-a----        10/17/2020   8:11 PM        2355200 temp_23808.pdb                                                                                                                                                                                                                           
-a----        10/17/2020   8:19 PM        1110016 temp_24816.pdb                                                                                                                                                                                                                           
-a----          9/9/2020   6:15 PM        2256896 temp_24964.pdb                                                                                                                                                                                                                           
-a----        10/11/2020  11:47 AM        2297856 temp_25124.pdb                                                                                                                                                                                                                           
-a----        10/18/2020  10:08 AM        2355200 temp_25172.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   9:23 PM        2306048 temp_26980.pdb                                                                                                                                                                                                                           
-a----        10/15/2020  10:25 PM        2355200 temp_27868.pdb                                                                                                                                                                                                                           
-a----          9/7/2020   7:28 PM        2273280 temp_27888.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   3:04 PM        2297856 temp_28168.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   8:14 PM        2297856 temp_28188.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   7:54 PM        2297856 temp_28756.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   8:08 PM        2297856 temp_29364.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   7:49 PM        2297856 temp_29512.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   8:07 PM        2297856 temp_30272.pdb                                                                                                                                                                                                                           
-a----        10/15/2020  10:29 PM        2355200 temp_31708.pdb                                                                                                                                                                                                                           
-a----        10/15/2020   7:59 PM        1093632 temp_3632.pdb                                                                                                                                                                                                                            
-a----        10/15/2020   3:37 PM        2297856 temp_5712.pdb                                                                                                                                                                                                                            
-a----        10/15/2020   7:45 PM        2297856 temp_6768.pdb                                                                                                                                                                                                                            
-a----        10/15/2020   7:57 PM        1093632 temp_6948.pdb                                                                                                                                                                                                                            
-a----        10/17/2020   8:19 PM         180736 temp_7120                                                                                                                                                                                                                                
-a----        10/17/2020   8:19 PM        1110016 temp_7120.pdb                                                                                                                                                                                                                            
-a----        10/17/2020   8:18 PM         180736 temp_8976                                                                                                                                                                                                                                
-a----        10/17/2020   8:18 PM        1110016 temp_8976.pdb                                                                                                                                                                                                                            
-a----        10/14/2020   9:16 PM        2297856 temp_9072.pdb                                                                                                                                                                                                                            
```

### CODE REVIEW

**Comment by jrvidal** [comment]
I think the proper solution would be to _delete_ those files instead of ignore them. Are you up for it @dzmitry-lahoda ? The relevant bits are in `exercise.rs` (functions `temp_file` and `clean`).

**Comment by dzmitry-lahoda** [comment]
I see. Checked `test exercise::test::test_clean ... ok` works for me, but that seems not called properly during run (if called at all). I am tentative for now a litter. Need to check spare time split.

**Comment by dzmitry-lahoda** [comment]
Possible root cause I abort via CTRL+C or like. So need to clean not only temp_PROCID, but any other temp_* from previous run.

**Comment by jrvidal** [comment]
I think we don't even attempt to delete anything with a `*.pdb` extension! There might be other underlying problems, as you mentioned, regarding CTRL+C behavior, where we don't properly clean files. But I think we could fix the `pdb` thing first easily.

**Comment by diannasoreil** [comment]
Let me know if this is still a problem, closing otherwise.

**Pull request closed without merging**
