### PR TITLE
fix watch command path execution

### LINKED ISSUE #126: "watch" is broken on windows
The issue seems to be that the call to verify(...) in main.rs:92 expects the path to be in Unix style (forward slashes instead of backslashes), so the later compare breaks.

I fixed this locally by just doing a string replace, but I guess a true Rustacean will fix this much more nicely so I didn't add a patch.

PS: It's also pretty inconvenient that "watch" doesn't continue with the next exercise once you fix the current one.

### PR DESCRIPTION
**Pull request by komaeda**
@hades32 @guttume could you test whether this works on windows by checking out the branch locally and running `cargo run watch`?

### CODE REVIEW

**Comment by guttume** [comment]
@komaeda I tried this branch also but it still sits on blank line when I make changes to my code. Including screenshot.
cmd
powershell

**Comment by komaeda** [comment]
well, this still seems to fix _something_, so i'll merge it

@bors r+

**Pull request merged**
