### PR TITLE
optimized the UI code

### PR DESCRIPTION
**Pull request by lucaplian**
I did a refactoring on the 'warn' and 'succes' macros. And created a new macro called print_emojis which did what the previous macros did but more generalized. I used the expr for "$emoji" and "$sign", because it can accept any UTF8 characters. In the case of "$color", I used the ident because it allowed me for customizability for the colour, because the variable to be used as an identifier(in my case a function)
I did this in order to avoid the duplication from the original code

### CODE REVIEW

**Comment by alexandruradovici** [comment]
Please describe your pull request.

**Comment by AnonimAnonim2245** [comment]
I did a refactoring on the 'warn' and 'succes' macros. And created a new macro called print_emojis which did what the previous macros did but more generalized. I used the expr for "$emoji" and "$sign", because it can accept any UTF8 characters. In the case of "$color", I used the ident because it allowed me for customizability for the colour, because the variable to be used as an identifier(in my case a function)

**Comment by AnonimAnonim2245** [comment]
I did this in order to avoid the duplication from the original code

**Comment by alexandruradovici** [comment]
> I did a refactoring on the 'warn' and 'succes' macros. And created a new macro called print_emojis which did what the previous macros did but more generalized. I used the expr for "$emoji" and "$sign", because it can accept any UTF8 characters. In the case of "$color", I used the ident because it allowed me for customizability for the colour, because the variable to be used as an identifier(in my case a function)

Please add it to the beginning of the pull request.

**Review by shadows-withal — APPROVED** [review]

**Pull request merged**
