### PR TITLE
refactor(arc1): improve readability by using functional style

### PR DESCRIPTION
**Pull request by Fointard**
Functional style is neat and shorter, I think it's good practice to promote it over imperative style.

### CODE REVIEW

**Review by diannasoreil — APPROVED** [review]

**Comment by diannasoreil** [comment]
@all-contributors please add @Fointard for content

**Comment by oriontvv** [comment]
@cyril-marpaud Hello, shouldn't it be like `let sum: u32 = child_numbers.iter().filter(|&n| *n % 8 == offset).sum();`?
because lambda argument is taken twice by reference instead of current version with `filter(|n| *n % 8 == offset)`. As I understand the implicit derefernce is saving situation here but I believe we should avoid implicit stuff in tutorials. What do you think about it?

**Comment by cyril-marpaud** [comment]
I agree, it could be cleaner without the implicit deref. Let's even do `filter(|&&n| n % 8 == offset)`, this way the type is explicit & no deref is needed at all, agreed ?

**Comment by oriontvv** [comment]
Yes, looks good. Will you fix it?

**Comment by cyril-marpaud** [comment]
> Yes, looks good. Will you fix it?

Done. Thank you for the heads up !

**Pull request merged**
