### PR TITLE
Update enums3.rs

### PR DESCRIPTION
**Pull request by fpolica91**
This will cause the function to keep failing, In order to pass I needed to remove a pair of quotes, not sure if this was intentional and my solution was wrong, but this was the only solution I was able to come up with.

### CODE REVIEW

**Comment by darnuria** [comment]
@fpolica91 hi! Thanks for your submission!

In these exercise I think the point is to write out an `enum Message` with changing as little as possible where the code is already written.

Did you consider using a `(u8, u8, u8)` for `Message::Color`?

Right now in your file I wonders you wrote in `Message` `Color(u8, u8, u8)`. It's not the same as `Color((u8, u8, u8))`,
These change might need to change your implementation in `fn process`.

But I also agree that it's not really clear and it's subtle in a beginner journey to see the difference to from the two types. So I think there is matter to discuss! :D

**Comment by darnuria** [comment]
@fmoko wanted to say #560 I think. :D

**Comment by fmoko** [comment]
you're right haha

**Comment by diannasoreil** [comment]
Closing along with #537.

**Pull request closed without merging**
