### PR TITLE
fix(iterators): Rename iterator3.rs

### LINKED ISSUE #155: iterator example names inconsistent
The iterator tests in `standard_library_types` are named `iterator3.rs` (singular) and `iterators4.rs` (plural). They should probably match.

### PR DESCRIPTION
**Pull request by miller-time**
fixes #155

### CODE REVIEW

**Comment by komaeda** [comment]
Ah, one small nit for all of your pull requests: Could you format them according to the Angular commit message standards? (https://gist.github.com/stephenparish/9941e89d80e2bc58a153#format-of-the-commit-message)

So, for this, something like `fix(iterators): Rename iterator3.rs`

**Comment by miller-time** [comment]
@komaeda done!

I see that clog was just added within the last couple days, and this commit format isn't mentioned in the README. Also, there is no CONTRIBUTING.md file so when you create a pull request there are no project-specific guidelines for formatting the PR, etc. 

I could take a stab at this, or else I would like to at least suggest that instructions be added somewhere. 🙂

**Comment by komaeda** [comment]
@miller-time Yep, haven't had time to write up any guidelines yet, unfortunately. The `fixes: <issue #>` is a good idea. I think I have some time right now, so I'll write up a simple `CONTRIBUTING.md`.

**Pull request merged**
